[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mllf"
version = "0.1.0"
description = "MLLF bias coefficient file handling"
readme = "README.md"
license = {text = "MIT"}
authors = [ {name = "Paige E. Bowling", email = "pbowling@umich.edu"} ]
maintainers = [ {name = "Paige E. Bowling", email = "pbowling@umich.edu"} ]
keywords = ["machine learning", "neural networks", "molecular dynamics", "multisite lambda dynamics"]
requires-python = ">=3.8"

dependencies = [
    "numpy>=1.24",
    "torch>=2.0",
]

[project.urls]
"Repository" = "https://github.com/pbowling/mllf"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "flake8",
]

rl = [
    "gym>=0.21.0",
    "ray[rllib]>=2.4.0,<3.0.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["src"]
