"""Create initial variables0.py in run_01/step_0, submit initialization job, and print the Graph.

This version writes `variables0.py` directly into `run_01/step_0/`
and places the submit script at `run_01/step_0/submit_init.sh`.
"""
import os
import subprocess
from pathlib import Path

from mllf.file_handling.write_bias_coeff import create_variables_py_from_template
from mllf.file_handling.read_rtf import parse_rtf_dir
"""Create initial variables0.py in run_01/step_0, submit initialization job, and print the Graph.

This version writes `variables0.py` directly into `run_01/step_0/` and places the
submit script at `run_01/step_0/submit_init.sh`. The job runs from the example
directory so `prep/` is found by `msld_flat.py`.
"""
import os
import subprocess
from pathlib import Path

from mllf.file_handling.write_bias_coeff import create_variables_py_from_template
from mllf.file_handling.read_rtf import parse_rtf_dir
from mllf.rl.graph import Graph


def main():
    repo_root = Path(__file__).resolve().parents[3]
    example_dir = repo_root / 'examples' / 'rl' / '14benz_solv_5.5'
    if not example_dir.is_dir():
        raise RuntimeError(f'Example directory not found: {example_dir}')

    # per-step dir (no extra subdirs)
    step_dir = example_dir / 'run_01' / 'step_0'
    step_dir.mkdir(parents=True, exist_ok=True)

    # template variables file in the example dir
    template = example_dir / 'variablesflat.py'
    vars0 = step_dir / 'variables0.py'

    if template.exists():
        create_variables_py_from_template(str(template), str(vars0), minimizeflag=False)
        print(f'Wrote variables file: {vars0}')
    else:
        # fallback minimal variables file
        vars0.write_text('# autogenerated\nminimizeflag=False\n')
        print(f'Wrote fallback variables file: {vars0}')

    # Optionally run initialization: call msld_flat.py with --vars-file
    if os.environ.get('RUN_INIT'):
        print('RUN_INIT set; submitting initialization job (may require scheduler/pyCHARMM)')
        submit_script = step_dir / 'submit_init.sh'
        # compute a path for vars file relative to example_dir so msld_flat can find 'prep/'
        vars_rel = vars0.relative_to(example_dir)
        submit_contents = f"""#!/bin/bash
#SBATCH --job-name=init_14benz
#SBATCH --output={'init_14benz.%j.out'}
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH -p gpu2080 --gres=gpu:1 
#SBATCH --export=ALL
#SBATCH --time=01:00:00

module load charmm

cd {example_dir}
python3 msld_flat.py --vars-file {vars_rel} --out-dir {vars_rel.parent} > {vars_rel.parent}/output.out
"""
        submit_script.write_text(submit_contents)
        try:
            # try to submit via sbatch
            res = subprocess.run(['sbatch', str(submit_script)], check=True, capture_output=True, text=True)
            print('Submitted with sbatch:', res.stdout.strip())
        except FileNotFoundError:
            # sbatch not available; fallback to local run (may fail if pyCHARMM not installed)
            print('sbatch not found: falling back to running msld_flat.py locally (may fail if pyCHARMM not configured)')
            try:
                # run from example_dir so prep/ is visible; pass out-dir as relative path to step
                subprocess.run(['python3', str(example_dir / 'msld_flat.py'), '--vars-file', str(vars_rel), '--out-dir', str(vars_rel.parent)], check=True, cwd=str(example_dir))
                print('Local initialization run finished.')
            except subprocess.CalledProcessError as e:
                print('Local initialization run failed: ', e)
        except subprocess.CalledProcessError as e:
            print('sbatch submission failed:', e)

    # Build the graph from RTF files and print summary
    rtf_results = parse_rtf_dir(str(example_dir))
    g = Graph.from_rtf_results(rtf_results)

    print(f'Graph: nodes={g.num_nodes}, edges={len(g.edges)}')
    print('\nNode metadata:')
    for idx in range(g.num_nodes):
        info = g.get_node_info(idx)
        print(f"Node {idx}: site={info.get('site')}, sub={info.get('sub')}, total_charge={info.get('total_charge')}, distinct_atoms={info.get('distinct_atom_types')}, solvent={info.get('solvent')}")


if __name__ == '__main__':
    main()
