"""Create variables0.py, run optional initialization, and print the Graph.

Usage:
  python init_and_print.py

Set environment variable RUN_INIT=1 to run `msld_flat.py --vars-file <path>` after creating variables0.py.
"""
import os
import subprocess
from pathlib import Path
from pprint import pprint

from mllf.file_handling.write_bias_coeff import create_variables_py_from_template
from mllf.file_handling.read_rtf import parse_rtf_dir
from mllf.rl.graph import Graph


def main():
    # repo_root: go up from tests/tools/... to the project root
    repo_root = Path(__file__).resolve().parents[4]
    example_dir = repo_root / 'examples' / 'rl' / '14benz_solv_5.5'
    if not example_dir.is_dir():
        raise RuntimeError(f'Example directory not found: {example_dir}')

    out_dir = example_dir / 'init_example_results'
    out_dir.mkdir(exist_ok=True)

    # template variables file in the example dir
    template = example_dir / 'variablesflat.py'
    vars0 = out_dir / 'variables0.py'

    if template.exists():
        create_variables_py_from_template(str(template), str(vars0), minimizeflag=False)
        print(f'Wrote variables file: {vars0}')
    else:
        # fallback minimal variables file
        vars0.write_text('# autogenerated\nminimizeflag=False\n')
        print(f'Wrote fallback variables file: {vars0}')

    # Optionally run initialization: call msld_flat.py with --vars-file
    if os.environ.get('RUN_INIT'):
        print('RUN_INIT set; submitting initialization job (may require scheduler/pyCHARMM)')
        submit_script = out_dir / 'submit_init.sh'
        # create an sbatch-style submit script that calls msld_flat.py with our vars file
        submit_contents = f"""#!/bin/bash
#SBATCH --job-name=init_14benz
#SBATCH --output=init_14benz.%j.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=01:00:00

cd {example_dir}
python {example_dir / 'msld_flat.py'} --vars-file {vars0}
"""
        submit_script.write_text(submit_contents)
        try:
            # try to submit via sbatch
            res = subprocess.run(['sbatch', str(submit_script)], check=True, capture_output=True, text=True)
            print('Submitted with sbatch:', res.stdout.strip())
            # attempt to extract job id and wait until the job no longer appears in squeue
            out = res.stdout.strip()
            # typical sbatch response: "Submitted batch job 123456"
            jid = None
            for part in out.split():
                if part.isdigit():
                    jid = part
                    break
            if jid:
                # if squeue is available, wait for job to finish
                try:
                    import shutil, time

                    if shutil.which('squeue') and os.environ.get('WAIT_FOR_JOB'):
                        print(f'Waiting for job {jid} to finish...')
                        while True:
                            sq = subprocess.run(['squeue', '-j', jid], capture_output=True, text=True)
                            if jid not in sq.stdout:
                                break
                            time.sleep(5)
                        print(f'Job {jid} no longer in squeue.')
                except Exception:
                    pass
        except FileNotFoundError:
            # sbatch not available; fallback to local run (may fail if pyCHARMM not installed)
            print('sbatch not found: falling back to running msld_flat.py locally (may fail if pyCHARMM not configured)')
            try:
                subprocess.run(['python3', str(example_dir / 'msld_flat.py'), '--vars-file', str(vars0)], check=True)
                print('Local initialization run finished.')
            except subprocess.CalledProcessError as e:
                print('Local initialization run failed: ', e)
        except subprocess.CalledProcessError as e:
            print('sbatch submission failed:', e)

    # Build the graph from RTF files and print summary
    rtf_results = parse_rtf_dir(str(example_dir))
    g = Graph.from_rtf_results(rtf_results)

    print(f'Graph: nodes={g.num_nodes}, edges={len(g.edges)}')
    print('\nNode metadata:')
    for idx in range(g.num_nodes):
        info = g.get_node_info(idx)
        print(f"Node {idx}: site={info.get('site')}, sub={info.get('sub')}, total_charge={info.get('total_charge')}, distinct_atoms={info.get('distinct_atom_types')}, solvent={info.get('solvent')}")


if __name__ == '__main__':
    main()
