"""Prepare the initial step directory and write variables0.py only.

Usage:
  python prepare_initial_step.py examples/rl/14benz_solv_5.5/config.yaml

This will create: run_dir/step_0/vars/variables0.py (from template) and the
step directory structure so that later per-step runs happen in separate folders
and won't overwrite each other's outputs.
"""
import sys
import yaml
from pathlib import Path
from mllf.file_handling.write_bias_coeff import create_variables_py_from_template


def main(cfg_path: Path):
    cfg = yaml.safe_load(cfg_path.read_text())
    run = cfg['runs'][0]
    base = Path(cfg_path).parent / run['run_dir']
    step = int(run.get('initial_step', 0))
    step_dir = base / f'step_{step}'
    # Only create the step folder itself; other files/directories will be
    # generated by the simulation when it runs (res/, dcd/, logs/, etc.).
    step_dir.mkdir(parents=True, exist_ok=True)

    template = Path(cfg_path).parent / run.get('vars_template', 'variablesflat.py')
    outpath = step_dir / 'variables0.py'
    if template.exists():
        create_variables_py_from_template(str(template), str(outpath), minimizeflag=False)
    else:
        outpath.write_text('# autogenerated\nminimizeflag=False\n')
    print('Wrote initial variables file:', outpath)
    print('Prepared step directory:', step_dir)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: python prepare_initial_step.py config.yaml')
        raise SystemExit(1)
    main(Path(sys.argv[1]))
